name: 'modern_data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  modern_data_warehouse:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      fact_orders:
        +materialized: incremental
        +unique_key: order_id
      +schema: MART